### ISSUE TITLE
Appliquer la feuille de style principale 

### ISSUE THREAD

**Issue by sandcha** [betagouv/leximpact-client#2]
La feuille de style [./app/styles/index.scss](https://github.com/betagouv/leximpact-client/blob/master/app/styles/index.scss) n'est pas appliquée à l'application.

L'activer ?

**Comment by DorineLam** [comment]
Oui, ce serait top, actuellement, je m'en sors avec ta solution "variable" :)

**Comment by maukoquiroga** [comment]
Fixed by #4
