### ISSUE TITLE
Intégrer les Twemojis (Bug)

### ISSUE THREAD

**Issue by DorineLam** [betagouv/leximpact-client#3]
Sur la branche ui-dorine : 
Bug d'implémentation des emojis de la bibliothèque iconify twemojis.
J'arrive à intégrer les emojis mais la moindre modif fait planter l'ensemble de l'interface avec ce message d'erreur : 

<img width="1095" alt="Capture d’écran 2019-05-02 à 17 48 26" src="https://user-images.githubusercontent.com/46896006/57088767-44e99900-6d03-11e9-91e7-c6fe854d3ea5.png">

Pourtant, le code suivant dans le composant "SimpleCard.jsx" fonctionnait : 
 ```
    import { Icon, InlineIcon } from '@iconify/react';
    import babyIcon from '@iconify/react/twemoji/baby';
    import manCurlyHaired from '@iconify/react/twemoji/man-curly-haired';
```
puis dans la card : 
```
    return (
        
            <Card className={classes.card}>
                <CardContent>
                    <Icon icon={babyIcon} style={styleIcons} />
                    <Icon icon={manCurlyHaired} />
                </CardContent>
            </Card>
```

**Comment by DorineLam** [comment]
Ça marche mais ça plante très régulièrement quand on touche aux "Icons"
<img width="1429" alt="Capture d’écran 2019-05-03 à 16 38 32" src="https://user-images.githubusercontent.com/46896006/57144706-e8997e80-6dc1-11e9-9536-ae765669d7a2.png">

**Comment by maukoquiroga** [comment]
Fixed by #5

**Comment by maukoquiroga** [comment]
Fixed by #5
